'use strict'

module.exports = {
  'react/display-name': 0,
  'react/forbid-prop-types': [2, { forbid: ['any'] }],
  'react/jsx-boolean-value': [2, 'always'],
  'react/jsx-closing-bracket-location': [2, 'line-aligned'],
  'react/jsx-curly-spacing': [2, 'never', { allowMultiline: true }],
  'react/jsx-equals-spacing': [2, 'never'],
  'react/jsx-first-prop-new-line': [2, 'multiline'],
  'react/jsx-handler-names': 0,
  'react/jsx-indent': [2, 2],
  'react/jsx-indent-props': [2, 2],
  'react/jsx-key': 2,
  'react/jsx-max-props-per-line': 0,
  'react/jsx-no-bind': [2, { allowArrowFunctions: true }],
  'react/jsx-no-duplicate-props': 2,
  'react/jsx-no-literals': 0,
  'react/jsx-no-undef': 2,
  'react/jsx-pascal-case': 2,
  'react/jsx-sort-props': 0,
  'react/jsx-space-before-closing': 2,
  'react/jsx-uses-react': 2,
  'react/jsx-uses-vars': 2,
  'react/no-danger': 1,
  'react/no-deprecated': [2, { react: '15.0.0' }],
  'react/no-did-mount-set-state': [2, 'allow-in-func'],
  'react/no-did-update-set-state': [2, 'allow-in-func'],
  'react/no-direct-mutation-state': 2,
  'react/no-is-mounted': 2,
  'react/no-multi-comp': 0,
  'react/no-set-state': 2,
  'react/no-string-refs': 2,
  'react/no-unknown-property': 2,
  'react/prefer-es6-class': 2,
  'react/prefer-stateless-function': 2,
  'react/prop-types': 2,
  'react/react-in-jsx-scope': 2,
  'react/require-extension': 0,
  'react/require-render-return': 2,
  'react/self-closing-comp': 2,
  'react/sort-comp': 2,
  'react/sort-prop-types': 2,
  'react/wrap-multilines': 2,
}
